import axios from "axios";
import type { NextPage } from "next";
import Image from "next/future/image";
import Head from "next/head";
import { useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";

import type { Inputs } from "../types";

const Home: NextPage = () => {
  const [qrCode, setQrCode] = useState<{ url: string } | null>(null);
  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => {
    axios
      .post("/api/qr-code", {
        requestedURL: data.requestedURL,
        size: data.size,
      })
      .then((res) => {
        setQrCode(res.data);
      })
      .catch((err) => console.log(err));
  };

  return (
    <>
      <Head>
        <title>QR Code Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-neutral-900 p-3">
        <h1 className="text-3xl font-bold text-white">QR Code Generator</h1>
      </header>

      <main className="flex flex-grow flex-col bg-neutral-100 px-6">
        <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col">
          <input
            defaultValue="https://ryelbanfield.me/"
            placeholder="URL"
            {...register("requestedURL", { required: true })}
            className="my-2 rounded-md border-2 border-gray-300 p-2"
          />

          {/* <select
            {...register("size")}
            className="mb-3 rounded-md border-2 border-gray-300 p-2"
          >
            <option value="small">Small</option>
            <option value="medium">Medium</option>
            <option value="large">Large</option>
          </select> */}

          <button
            type="submit"
            className="rounded-md bg-neutral-900 p-2 text-white"
          >
            Generate QR Code
          </button>
        </form>
        {qrCode && (
          <div className="relative m-auto flex h-64 w-64 items-center justify-center">
            <Image
              src={qrCode.url}
              alt="QR Code"
              fill
              className="my-3 rounded-md border-2 border-gray-300"
            />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
